### ISSUE TITLE
Found a broken link in ThomasHabets/arping!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1056]
@ThomasHabets, there's a [broken link](http://www.packetfactory.net/libnet) in the README of [one of your repositories](https://github.com/ThomasHabets/arping).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://www.packetfactory.net/libnet and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by ThomasHabets** [comment]
Fixed

**Comment by ThomasHabets** [comment]
@sam-github you may want to update the libnet package at https://github.com/sam-github/libnet too
