### ISSUE TITLE
Found a broken link in ThomasHabets/gtping!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1058]
@ThomasHabets, there's a [broken link](http://www.3gpp.org/ftp/Specs/2009-03/Rel-8/29_series/29274-811.zip) in the README of [one of your repositories](https://github.com/ThomasHabets/gtping).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://www.3gpp.org/ftp/Specs/2009-03/Rel-8/29_series/29274-811.zip and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by ThomasHabets** [comment]
Same as https://github.com/evuez/github-links-checker/issues/1057, but the link next to it.
