### ISSUE TITLE
Found a broken link in mneumann/wee!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1063]
@mneumann, there's a [broken link](http://seaside.st/) in the README of [one of your repositories](https://github.com/mneumann/wee).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://seaside.st/ and an `HTTP 403` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by mneumann** [comment]
false alarm

**Comment by evuez** [comment]
Sorry for that!
