### ISSUE TITLE
Found a broken link in abh/djbdns!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1087]
@abh, there's a [broken link](http://cr.yp.to/djbdns/install.html) in the README of [one of your repositories](https://github.com/abh/djbdns).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://cr.yp.to/djbdns/install.html and an `HTTP 501` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by abh** [comment]
nope, your bot is wrong.
