### ISSUE TITLE
Found a broken link in jmettraux/pilatus!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1088]
@jmettraux, there's a [broken link](http://github.com/jmettraux/ruote/commit/c36912c9bde3ff7ddbbaa48ee971acb76ccb1744">http://github.com/jmettraux/ruote/commit/c36912c9bde3ff7ddbbaa48ee971acb76ccb1744</a) in the README of [one of your repositories](https://github.com/jmettraux/pilatus).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://github.com/jmettraux/ruote/commit/c36912c9bde3ff7ddbbaa48ee971acb76ccb1744">http://github.com/jmettraux/ruote/commit/c36912c9bde3ff7ddbbaa48ee971acb76ccb1744</a and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by jmettraux** [comment]
Will not fix. The project is dead, I do not want, by making a commit, to give the impression that the project is alive.
