### ISSUE TITLE
Found a broken link in jimm/midilib!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1196]
@jimm, there's a [broken link](http://www.borg.com/~jglatt/tech/midifile.htm) in the README of [one of your repositories](https://github.com/jimm/midilib).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://www.borg.com/~jglatt/tech/midifile.htm and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by jimm** [comment]
Fixed.
