### ISSUE TITLE
Found a broken link in ahwayakchih/templatedtextformatters!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1223]
@ahwayakchih, there's a [broken link](http://www.impallari.com/lobster/) in the README of [one of your repositories](https://github.com/ahwayakchih/templatedtextformatters).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://www.impallari.com/lobster/ and an `HTTP 503` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by ahwayakchih** [comment]
Works here.

**Comment by evuez** [comment]
Indeed, sorry for that!
