### ISSUE TITLE
Found a broken link in damog/feedbag!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1295]
@damog, there's a [broken link](http://github.com/damog/feedbag/master/COPYING) in the README of [one of your repositories](https://github.com/damog/feedbag).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://github.com/damog/feedbag/master/COPYING and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by damog** [comment]
Thanks, I've now fixed it.
