### ISSUE TITLE
Found a broken link in hdon/ggbg!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1315]
@hdon, there's a [broken link](http://sqlkit.argolinux.org/download/goocanvas.pyd) in the README of [one of your repositories](https://github.com/hdon/ggbg).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://sqlkit.argolinux.org/download/goocanvas.pyd and an `HTTP 404` was returned.

_This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!_

**Comment by hdon** [comment]
That broken link is a feature, robot. It let's visitors know that this repository is unmaintained.
