### ISSUE TITLE
Found a broken link in myobie/turbine!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1328]
@myobie, there's a [broken link](http://www.example.com/trackback/5) in the README of [one of your repositories](https://github.com/myobie/turbine).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://www.example.com/trackback/5 and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by myobie** [comment]
You might want to whitelist example.com

**Comment by evuez** [comment]
Will do that... Thanks and sorry for that :)
