### ISSUE TITLE
Found a broken link in quamen/quamen.github.com!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1334]
@quamen, there's a [broken link](http://github.com/quamen/qumen.github.com) in the README of [one of your repositories](https://github.com/quamen/quamen.github.com).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://github.com/quamen/qumen.github.com and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by quamen** [comment]
Fixed.
