### ISSUE TITLE
Found a broken link in tokuhirom/unco!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1395]
@tokuhirom, there's a [broken link](http://kanasoku.blog82.fc2.com/blog-entry-9347.html) in the README of [one of your repositories](https://github.com/tokuhirom/unco).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://kanasoku.blog82.fc2.com/blog-entry-9347.html and an `HTTP 404` was returned.

_This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!_

**Comment by tokuhirom** [comment]
Fixed. Please  close this issue.
