### ISSUE TITLE
Found a broken link in sunny/orouxgami!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1398]
@sunny, there's a [broken link](http://orouxgami.rousseur.org/) in the README of [one of your repositories](https://github.com/sunny/orouxgami).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://orouxgami.rousseur.org/ and an `HTTP 403` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by sunny** [comment]
Fixed! Thanks.
