### ISSUE TITLE
Found a broken link in akm/schema_comments!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#1412]
@akm, there's a [broken link](http://github.com/rotuka/annotate_models) in the README of [one of your repositories](https://github.com/akm/schema_comments).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://github.com/rotuka/annotate_models and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by akm** [comment]
@evuez Thank you for your issue. I removed the link. His/Her account seems to be removed.
