### ISSUE TITLE
Found a broken link in lazyatom/engines!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#409]
@lazyatom, there's a [broken link](http://rails-engines.org/development/common-issues-when-overloading-code-from-plugins/) in the README of [one of your repository](https://github.com/lazyatom/engines).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://rails-engines.org/development/common-issues-when-overloading-code-from-plugins/ and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by lazyatom** [comment]
Fixed in lazyatom/rails-engines@d36f415c1ae3899a99678796df8a8046a15820c5
