### ISSUE TITLE
Found a broken link in tapajos/brazilian-rails!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#425]
@tapajos, there's a [broken link](https://github.com/rafaeldx7) in the README of [one of your repository](https://github.com/tapajos/brazilian-rails).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to https://github.com/rafaeldx7 and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by tapajos** [comment]
fixed
