### ISSUE TITLE
Found a broken link in pat/active-matchers!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#427]
@pat, there's a [broken link](http://github.com/freelancing-god/active-matchers.git) in the README of [one of your repository](https://github.com/pat/active-matchers).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://github.com/freelancing-god/active-matchers.git and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by pat** [comment]
Fixed.
