### ISSUE TITLE
Found a broken link in mfilej/ruby-sass-tmbundle!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#506]
@mfilej, there's a [broken link](http://github.com/giannichiappetta) in the README of [one of your repository](https://github.com/mfilej/ruby-sass-tmbundle).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://github.com/giannichiappetta and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by mfilej** [comment]
Fixed by removing the repo.
