### ISSUE TITLE
Found a broken link in jodosha/cached-models!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#565]
@jodosha, there's a [broken link](http://www.lucaguidi.com/pages/cached_models) in the README of [one of your repository](https://github.com/jodosha/cached-models).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://www.lucaguidi.com/pages/cached_models and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by jodosha** [comment]
Hello there, `cached_models` is deprecated and no longer maintained. That `/pages` prefix were introduced before GH pages was invented. I don't have interest into introducing that dead page again. Thank you.
