### ISSUE TITLE
Found a broken link in verhoevenv/jumpnbump-wii!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#701]
@verhoevenv, there's a [broken link](http://www.brainchilddesign.com/games/jumpnbump/index.html) in the README of [one of your repository](https://github.com/verhoevenv/jumpnbump-wii).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://www.brainchilddesign.com/games/jumpnbump/index.html and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by verhoevenv** [comment]
Thank you, fixed!
