### ISSUE TITLE
Found a broken link in apenwarr/nitlog!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#716]
@apenwarr, there's a [broken link](http://foo.com/nitlog/?m=200411#05) in the README of [one of your repository](https://github.com/apenwarr/nitlog).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://foo.com/nitlog/?m=200411#05 and an `HTTP 404` was returned.

_This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!_

**Comment by apenwarr** [comment]
That's just an example URL, not one intended to be used.
