### ISSUE TITLE
Found a broken link in henrik/augmentations!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#777]
@henrik, there's a [broken link](http://dancejam.com) in the README of [one of your repository](https://github.com/henrik/augmentations).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://dancejam.com and an `HTTP 403` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by henrik** [comment]
Thank you. I'll leave this as-is.
