### ISSUE TITLE
Found a broken link in quad/moxie!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#865]
@quad, there's a [broken link](http://somethingaboutorange.com/mrl/projects/nose/) in the README of [one of your repository](https://github.com/quad/moxie).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://somethingaboutorange.com/mrl/projects/nose/ and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by quad** [comment]
Thank you. Fixed in quad/moxie@871de9e
