### ISSUE TITLE
Found a broken link in vanntastic/silverstreak!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#901]
@vanntastic, there's a [broken link](http://code.google.com/apis/ajaxlibs/documentation/index.html) in the README of [one of your repository](https://github.com/vanntastic/silverstreak).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://code.google.com/apis/ajaxlibs/documentation/index.html and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by vanntastic** [comment]
just fixed it - thx for update
