### ISSUE TITLE
Found a broken link in jmettraux/ruote_plugin!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#903]
@jmettraux, there's a [broken link](http://woss.name/2008/04/09/using-git-submodules-to-track-vendorrails/) in the README of [one of your repository](https://github.com/jmettraux/ruote_plugin).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://woss.name/2008/04/09/using-git-submodules-to-track-vendorrails/ and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by jmettraux** [comment]
Will not fix, the project is dead, I do not want, by a commit, give the impression that it is still alive.
