### ISSUE TITLE
Found a broken link in mislav/user-scripts!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#922]
@mislav, there's a [broken link](http://mislav.uniqpath.com/user-scripts/endless-tweets/) in the README of [one of your repository](https://github.com/mislav/user-scripts).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://mislav.uniqpath.com/user-scripts/endless-tweets/ and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by mislav** [comment]
It's fixed now (removed the link).

BTW, the text should say "one of your repositories" instead of "one of your repository". :wink:

**Comment by evuez** [comment]
Thanks, I fixed that :)
