### ISSUE TITLE
Found a broken link in bscofield/stammer!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#928]
@bscofield, there's a [broken link](http://www.yammer.com/company/api_doc) in the README of [one of your repository](https://github.com/bscofield/stammer).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://www.yammer.com/company/api_doc and an `HTTP 404` was returned.

_This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!_

**Comment by bscofield** [comment]
Archived the repo; please feel free to close this!
