### ISSUE TITLE
Found a broken link in jeremiah/tapat!

### ISSUE THREAD

**Issue by evuez** [evuez/github-links-checker#959]
@jeremiah, there's a [broken link](http://testanything.org/wiki/index.php/Main_Page) in the README of [one of your repository](https://github.com/jeremiah/tapat).
You should fix it so that users don't get confused while browsing it!

> A `HEAD` request was sent to http://testanything.org/wiki/index.php/Main_Page and an `HTTP 404` was returned.

*This is a bot-generated issue, reply to this issue if this link wasn't broken or if you fixed it so I can close it!*

**Comment by jeremiah** [comment]
Fixed.
